server:
  # this is required to disable SSL redirection, as ingress handles this
  extraArgs:
  - --insecure
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      nginx.org/hsts: "false"
      cert-manager.io/cluster-issuer: issuer
    hosts:
    - argocd.lab.moabukar.co.uk
    tls:
    - secretName: argocd-ingress-tls
      hosts:
      - argocd.lab.moabukar.co.uk
