apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <email>
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          hostedZoneID: <Route53 Hosted Zone ID>
          region: us-east-2
      selector:
        dnsZones:
        - "lab.moabukar.co.uk"
    - http01:
        ingress:
          class: nginx
