argo-cd:

  server:
    # this is required to disable SSL redirection, as ingress handles this
    extraArgs:
    - --insecure
    service:
      type: ClusterIP
    ingress:
      hosts:
      - argocd.lab.moabukar.co.uk
      tls:
      - secretName: argocd-ingress-tls
        hosts:
        - argocd.lab.moabukar.co.uk
